# This pipeline validates that a PR's already built Metrics Adapter image will
# succeed with K8s v 1.10-1.13

jobs:
- template: .azdevops/cluster-test.yaml
  displayName: "K8s v1.10"
  parameters:
    DOCKER_VERSION: '18.06.1~ce~3-0~ubuntu'
    KUBERNETES_VERSION: '1.10.12'

- template: .azdevops/cluster-test.yaml
  displayName: "K8s v1.11"
  parameters:
    DOCKER_VERSION: '17.03.3~ce-0~ubuntu-xenial'
    KUBERNETES_VERSION: '1.11.6'

- template: .azdevops/cluster-test.yaml
  displayName: "K8s v1.12"
  parameters:
    DOCKER_VERSION: '18.06.1~ce~3-0~ubuntu'
    KUBERNETES_VERSION: '1.12.4'

- template: .azdevops/cluster-test.yaml
  displayName: "K8s v1.13"
  parameters:
    DOCKER_VERSION: '18.06.1~ce~3-0~ubuntu'
    KUBERNETES_VERSION: '1.13.1'