# This pipeline is the template for a deployment test given K8s and Docker
# verions 

parameters:
  dockerVersion: ''
  kubernetesVersion: ''
  displayName: ''
  queueName: ''

jobs:
- job:
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
  - group: 'Metrics Adapter'

  steps:
  - displayName: 'Print version details'
    script: |
      echo "This build uses the following versions:"
      echo "Kubernetes: ${{ parameters.kubernetesVersion }}"
      echo "Minikube: $(MINIKUBE_VERSION)"
      echo "Helm: $(HELM_VERSION)"
      echo "Docker: ${{ parameters.dockerVersion }}"

# Go workspace setup from https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops
  - displayName: 'Set up the Go workspace'
    script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(go) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'  
      cd $(modulePath) 
      go get -v -t -d ./... 
      if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      fi
    
  - displayName: 'Install docker (must continue on error)'
    script: |
      chmod +x *.sh 
      ./install-docker.sh
    workingDirectory: '$(modulePath)/.azdevops/0_install'
    env: 
      DOCKER_VERSION: ${{ parameters.dockerVersion }}

  - displayName: 'Install everything else'
    script: |
      ./install-misc.sh
      ./install-crictl.sh
      ./install-kubectl.sh
      ./install-minikube.sh
      ./install-helm.sh
    workingDirectory: '$(modulePath)/.azdevops/0_install'
    env: 
      KUBERNETES_VERSION: ${{ parameters.kubernetesVersion }}

  - displayName: 'Cluster set up & Go get'
    script: |
      chmod +x *.sh
      ./start-cluster.sh
      ./go-get.sh
      ./check-cluster.sh
      ./init-tiller.sh
    workingDirectory: '$(modulePath)/.azdevops/1_setup'
    env: 
      KUBERNETES_VERSION: ${{ parameters.kubernetesVersion }}

  - displayName: 'Deploy metrics server & create local values file'
    script: |
      chmod +x *.sh
      ./deploy-metrics-server.sh
      ./gen-values-file.sh
    workingDirectory: '$(modulePath)/.azdevops/2_deploy'
    failOnStderr: true
    env:
      VERSION: $(Build.TriggeredBy.BuildId)
  
  - displayName: 'Run e2e test script (deploy adapter & test functionality)'
    script: |
      chmod +x *.sh
      ./run-e2e.sh
    workingDirectory: '$(modulePath)/hack'
    failOnStderr: true
    env:
      SERVICEBUS_CONNECTION_STRING: $(SERVICEBUS_CONNECTION_STRING)
      SERVICEBUS_QUEUE_NAME: ${{ parameters.queueName }}
      SP_CLIENT_ID: $(SP_CLIENT_ID)
      SP_TENANT_ID: $(SP_TENANT_ID)
      SP_CLIENT_SECRET: $(SP_CLIENT_SECRET)

  - displayName: 'Debug information'
    script: |
      chmod +x *.sh
      ./output-details.sh
    workingDirectory: '$(modulePath)/.azdevops/4_output'
    failOnStderr: true
